version: '3.5'

services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=users #postgres
      - POSTGRES_SSLMODE=disable
    image: postgres:15.0-alpine3.16
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  gateway1:
    container_name: gateway1
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    restart: always
    command: ./gateway1
    ports:
      - "8080:8080"
    depends_on:
      - nats
    environment:
      - CONFIG_PATH=/go/gateway/internal/config/config.yaml
    networks:
      - nats

  consumer:
    container_name: consumer1
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    restart: always
    command: ./consumer1
    depends_on:
      - postgres
      - nats
    environment:
      - CONFIG_PATH=/go/consumer/internal/config/config.yaml
    networks:
      - nats

  nats:
    container_name: nats
    image: nats-streaming:latest
    networks:
      - nats
    restart: always
    command:
      - "-m"
      - "8222"
    ports:
      - "4222:4222"
      - "8222:8222"

networks:
  nats:
    name: nats