// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	user "go-nats-pub-sub-restapi-postgresql/consumer/internal/entity"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, tx, userDTO
func (_m *UserRepository) CreateUser(ctx context.Context, tx *sqlx.Tx, userDTO *user.User) error {
	ret := _m.Called(ctx, tx, userDTO)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *user.User) error); ok {
		r0 = rf(ctx, tx, userDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, id, tx
func (_m *UserRepository) GetBalance(ctx context.Context, id string, tx *sqlx.Tx) (float32, error) {
	ret := _m.Called(ctx, id, tx)

	var r0 float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *sqlx.Tx) (float32, error)); ok {
		return rf(ctx, id, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *sqlx.Tx) float32); ok {
		r0 = rf(ctx, id, tx)
	} else {
		r0 = ret.Get(0).(float32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *sqlx.Tx) error); ok {
		r1 = rf(ctx, id, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceAccrual provides a mock function with given fields: ctx, tx, userDTO
func (_m *UserRepository) UserBalanceAccrual(ctx context.Context, tx *sqlx.Tx, userDTO *user.User) error {
	ret := _m.Called(ctx, tx, userDTO)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *user.User) error); ok {
		r0 = rf(ctx, tx, userDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
